[build]

base = "homepage/"

publish = "build/"

command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

from = "https://averynova.tk/*"
to = "https://sapphire.saastamoinen.tk"
status = 200
